// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CricketPlayers string
	CricketTeams   string
	Migrations     string
	TeamPlayers    string
}{
	CricketPlayers: "cricket_players",
	CricketTeams:   "cricket_teams",
	Migrations:     "migrations",
	TeamPlayers:    "team_players",
}
