// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CricketGrounds string
	CricketPlayers string
	CricketTeams   string
	GroundBookings string
	Migrations     string
	Payments       string
	TeamPlayers    string
}{
	CricketGrounds: "cricket_grounds",
	CricketPlayers: "cricket_players",
	CricketTeams:   "cricket_teams",
	GroundBookings: "ground_bookings",
	Migrations:     "migrations",
	Payments:       "payments",
	TeamPlayers:    "team_players",
}
