// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("CricketGrounds", testCricketGroundsUpsert)

	t.Run("CricketPlayers", testCricketPlayersUpsert)

	t.Run("CricketTeams", testCricketTeamsUpsert)

	t.Run("GroundBookings", testGroundBookingsUpsert)

	t.Run("Migrations", testMigrationsUpsert)

	t.Run("Payments", testPaymentsUpsert)

	t.Run("TeamPlayers", testTeamPlayersUpsert)
}
